### ISSUE TITLE
Meet a problem using Kitgen tool

### ISSUE THREAD

**Issue by GrantZheng** [go-kit/kit#648] opened 2017-12-21 06:22 UTC
Hi:
I meet a problem when I make project with the testdata by kitgen tool: 
`
kitgen -repo-layout default in.go

2017/12/21 14:13:46 generating AST: formatNodes: endpoints/endpoints.go:9:20: unknown escape sequence (and 4 more errors)
`
![image](https://user-images.githubusercontent.com/8568462/34243131-5fe88850-e65a-11e7-94c0-5d2cff14b6a3.png)

And, use "kitgen -repo-layout flat in.go" is ok.

Thanks

**Comment by ZachEddy** [comment] 2017-12-21 09:29
I'm not able to reproduce the issue. Here are the steps I followed:

```bash
# go to foo example
$ cd go/src/github.com/go-kit/kit/cmd/kitgen/testdata/foo

# show latest go kit commit
$ git rev-parse HEAD
953e747656a7bbb5e1f998608b460458958b70cc

# show version of go
$ go version
go version go1.9.1 darwin/amd64

# build kitgen binary to $GOBIN
$ go install ...

# generate server (no errors)
$ kitgen -repo-layout default in.go

# show generated files
$ tree -C -A .
.
├── default
│   ├── endpoints
│   │   └── endpoints.go
│   ├── http
│   │   └── http.go
│   └── service
│       └── service.go
├── endpoints
│   └── endpoints.go
├── flat
│   └── gokit.go
├── http
│   └── http.go
├── in.go
└── service
    └── service.go
```

Hope this helped!

**Comment by lewgun** [comment] 2017-12-26 05:54
@ZachEddy I reproduced the issue on Windows @nyarly

**Comment by nyarly** [comment] 2018-01-05 22:58
Is there something Windows specific here? It's been a really long time since I've touched that platform, so I admit to being at something of a loss.

**Comment by peterbourgon** [comment] 2018-03-16 17:01
I'll close this unless

**Closed by peterbourgon** 2018-03-16 17:01 UTC

**Comment by r1se** [comment] 2018-11-14 16:17
I have same problem on windows

**Comment by wolfvavea** [comment] 2018-12-04 07:39
just try it and found the same issue on windows,.
