### ISSUE TITLE
grpc 1.6.0

### ISSUE THREAD

**Issue by spiffcp** [go-kit/kit#621] opened 2017-10-07 18:33 UTC
It looks like this release on August 30th for grpc brought in some API changes that conflict with the grpc package (gokit/transport/grpc): client and server files respectively.

https://github.com/grpc/grpc-go/releases/tag/v1.6.0
https://github.com/grpc/grpc-go/pull/1392

error encountered:
go-kit/kit/transport/grpc/client.go:94:9: undefined: metadata.NewContext
go-kit/kit/transport/grpc/server.go:76:12: undefined: metadata.FromContext

These methods were removed from the metadata package in the newest grpc release.

If possible I would like to write an implementation that updates the methods used by the grpc package so that gokit is inline with the newest API specification.

**Comment by basvanbeek** [comment] 2017-10-07 18:47
Hi @spiffcp,

This has already landed in master but the latest release of Go kit does not include this change.

@peterbourgon: maybe time to cut a new release?

**Comment by basvanbeek** [comment] 2017-10-07 18:49
closing... dupe of #618

**Closed by basvanbeek** 2017-10-07 18:49 UTC
