### ISSUE TITLE
Cannot debug programs that use go-kit

### ISSUE THREAD

**Issue by rumbergd** [go-kit/kit#567] opened 2017-07-10 15:12 UTC
I see this issue in Gogland and VSCode IDEs. If I try debugging a service that uses go-kit, the process fails to start. The debugger panics, and the process is terminated.
The cause of this panic is in go-stack package (github.com/go-stack/stack), which is used by go-kit 
 github.com/go-kit/kit/log.
When I start the program without debugging, everything works fine. When I start with debugging, findSigpanic() in stack.go causes debugger to panic. The comment for this functions says "findSigpanic intentionally executes faulting code to generate a stack trace containing an entry for runtime.sigpanic". I'm assuming it should give you stack traces during runtime, however it throws the debugger off. 
The issue is really annoying, and prevents me from using some good go-kit features.

**Comment by peterbourgon** [comment] 2017-07-10 15:25
Duplicate of #555.

**Closed by peterbourgon** 2017-07-10 15:25 UTC

**Comment by peterbourgon** [comment] 2017-07-10 17:43
@rumbergd Apparently this is fixed in the latest version, can you try it out and report back if it doesn't work on the other ticket? Thanks!

**Comment by rumbergd** [comment] 2017-07-11 19:58
Thank you. Yes, apparently PR was merged yesterday
